# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: IMRT100
author: JGG/TBN/IMS
logo: nmbu.png
copyright: "2024"

exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", README.md]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: remove-warn

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jggjevestad/IMRT100  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: nmbu.png
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
  config:
    language: "no"